"""Canonical lifecycle path and stage vocabulary.

Source: 03_core_specifications/00_canonical_object_lifecycle/
0_canonical_object_lifecycle.md Sections 3 and 10.

Lifecycle path uses the existing `PathType` enum (schemas/enums.py, sourced from
1_common_schema_dto.md Section 12.3) rather than a second, duplicate enum — Section 3's
Standard / Emergency Fast-Path / Monitoring-Only paths are the same three paths
`PathType` already represents.

This module defines lifecycle structure only. It does not create orchestration,
approval, Safety Gate, dispatch, or physical-control behavior.
"""

from __future__ import annotations

from enum import Enum

from ledo_ontology_core.framework.schemas.enums import PathType

__all__ = [
    "PathType",
    "LifecycleStage",
    "STANDARD_LIFECYCLE_STAGES",
    "EMERGENCY_FAST_PATH_STAGES",
    "MONITORING_ONLY_STAGES",
    "LIFECYCLE_STAGE_ORDER",
    "FAILURE_STAGES",
]


class LifecycleStage(str, Enum):
    """Canonical lifecycle stages and failure states from Section 10."""

    RAW_RECEIVED = "RAW_RECEIVED"
    ENVELOPED = "ENVELOPED"
    PATH_CLASSIFIED = "PATH_CLASSIFIED"
    CANONICALIZED = "CANONICALIZED"
    ONTOLOGY_BOUND = "ONTOLOGY_BOUND"
    EVIDENCE_ATTACHED = "EVIDENCE_ATTACHED"
    WORLD_STATE_UPDATED = "WORLD_STATE_UPDATED"
    CANDIDATE_GENERATED = "CANDIDATE_GENERATED"
    DECISION_ROUTED = "DECISION_ROUTED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVED_ACTION_CREATED = "APPROVED_ACTION_CREATED"
    RUNTIME_VALIDATION_INPUT_CREATED = "RUNTIME_VALIDATION_INPUT_CREATED"
    RUNTIME_VALIDATION_RESULT_CREATED = "RUNTIME_VALIDATION_RESULT_CREATED"
    SAFETY_GATE_PASSED = "SAFETY_GATE_PASSED"
    SAFETY_GATE_BLOCKED = "SAFETY_GATE_BLOCKED"
    EXECUTION_REQUEST_CREATED = "EXECUTION_REQUEST_CREATED"
    EXTERNAL_REQUEST_DISPATCHED = "EXTERNAL_REQUEST_DISPATCHED"
    FEEDBACK_RECEIVED = "FEEDBACK_RECEIVED"
    WORLD_STATE_RECONCILED = "WORLD_STATE_RECONCILED"
    AUDIT_CLOSED = "AUDIT_CLOSED"

    EMERGENCY_DETECTED = "EMERGENCY_DETECTED"
    MINIMAL_TARGET_BOUND = "MINIMAL_TARGET_BOUND"
    LOCAL_EMERGENCY_POLICY_PASSED = "LOCAL_EMERGENCY_POLICY_PASSED"
    EMERGENCY_APPROVED_ACTION_CREATED = "EMERGENCY_APPROVED_ACTION_CREATED"
    EMERGENCY_RUNTIME_VALIDATION_INPUT_CREATED = (
        "EMERGENCY_RUNTIME_VALIDATION_INPUT_CREATED"
    )
    EMERGENCY_RUNTIME_VALIDATION_RESULT_CREATED = (
        "EMERGENCY_RUNTIME_VALIDATION_RESULT_CREATED"
    )
    EMERGENCY_SAFETY_GATE_PASSED = "EMERGENCY_SAFETY_GATE_PASSED"
    EMERGENCY_SAFETY_GATE_BLOCKED = "EMERGENCY_SAFETY_GATE_BLOCKED"
    EMERGENCY_EXECUTION_REQUEST_CREATED = "EMERGENCY_EXECUTION_REQUEST_CREATED"
    POST_HOC_ONTOLOGY_BINDING = "POST_HOC_ONTOLOGY_BINDING"

    LIGHTWEIGHT_CANONICALIZED = "LIGHTWEIGHT_CANONICALIZED"
    BASIC_BOUND_OR_KNOWN_SOURCE_MAPPED = "BASIC_BOUND_OR_KNOWN_SOURCE_MAPPED"
    METRIC_UPDATED = "METRIC_UPDATED"
    OPTIONAL_AUDIT_SAMPLED = "OPTIONAL_AUDIT_SAMPLED"

    REJECTED_INVALID_SCHEMA = "REJECTED_INVALID_SCHEMA"
    REJECTED_UNKNOWN_SOURCE = "REJECTED_UNKNOWN_SOURCE"
    REJECTED_BINDING_FAILED = "REJECTED_BINDING_FAILED"
    REJECTED_LOW_CONFIDENCE = "REJECTED_LOW_CONFIDENCE"
    REJECTED_STALE_STATE = "REJECTED_STALE_STATE"
    REJECTED_INSUFFICIENT_EVIDENCE = "REJECTED_INSUFFICIENT_EVIDENCE"
    REJECTED_POLICY_DENIED = "REJECTED_POLICY_DENIED"
    REJECTED_APPROVAL_MISSING = "REJECTED_APPROVAL_MISSING"
    REJECTED_CAPABILITY_UNAVAILABLE = "REJECTED_CAPABILITY_UNAVAILABLE"
    REJECTED_TARGET_INVALID = "REJECTED_TARGET_INVALID"
    REJECTED_ADAPTER_UNAVAILABLE = "REJECTED_ADAPTER_UNAVAILABLE"
    EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    FEEDBACK_MISSING = "FEEDBACK_MISSING"
    FEEDBACK_CONFLICT = "FEEDBACK_CONFLICT"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    MANUAL_OVERRIDE_REQUIRED = "MANUAL_OVERRIDE_REQUIRED"
    AUDIT_INCOMPLETE = "AUDIT_INCOMPLETE"
    UNCLASSIFIED_ENTITY_DETECTED = "UNCLASSIFIED_ENTITY_DETECTED"
    MAPPING_REVIEW_REQUIRED = "MAPPING_REVIEW_REQUIRED"
    POLICY_CONTEXT_STALE = "POLICY_CONTEXT_STALE"


STANDARD_LIFECYCLE_STAGES: tuple[LifecycleStage, ...] = (
    LifecycleStage.RAW_RECEIVED,
    LifecycleStage.ENVELOPED,
    LifecycleStage.PATH_CLASSIFIED,
    LifecycleStage.CANONICALIZED,
    LifecycleStage.ONTOLOGY_BOUND,
    LifecycleStage.EVIDENCE_ATTACHED,
    LifecycleStage.WORLD_STATE_UPDATED,
    LifecycleStage.CANDIDATE_GENERATED,
    LifecycleStage.DECISION_ROUTED,
    LifecycleStage.APPROVAL_PENDING,
    LifecycleStage.APPROVAL_GRANTED,
    LifecycleStage.APPROVED_ACTION_CREATED,
    LifecycleStage.RUNTIME_VALIDATION_INPUT_CREATED,
    LifecycleStage.RUNTIME_VALIDATION_RESULT_CREATED,
    LifecycleStage.SAFETY_GATE_PASSED,
    LifecycleStage.EXECUTION_REQUEST_CREATED,
    LifecycleStage.EXTERNAL_REQUEST_DISPATCHED,
    LifecycleStage.FEEDBACK_RECEIVED,
    LifecycleStage.WORLD_STATE_RECONCILED,
    LifecycleStage.AUDIT_CLOSED,
)

EMERGENCY_FAST_PATH_STAGES: tuple[LifecycleStage, ...] = (
    LifecycleStage.RAW_RECEIVED,
    LifecycleStage.ENVELOPED,
    LifecycleStage.EMERGENCY_DETECTED,
    LifecycleStage.MINIMAL_TARGET_BOUND,
    LifecycleStage.LOCAL_EMERGENCY_POLICY_PASSED,
    LifecycleStage.EMERGENCY_APPROVED_ACTION_CREATED,
    LifecycleStage.EMERGENCY_RUNTIME_VALIDATION_INPUT_CREATED,
    LifecycleStage.EMERGENCY_RUNTIME_VALIDATION_RESULT_CREATED,
    LifecycleStage.EMERGENCY_SAFETY_GATE_PASSED,
    LifecycleStage.EMERGENCY_EXECUTION_REQUEST_CREATED,
    LifecycleStage.EXTERNAL_REQUEST_DISPATCHED,
    LifecycleStage.FEEDBACK_RECEIVED,
    LifecycleStage.POST_HOC_ONTOLOGY_BINDING,
    LifecycleStage.WORLD_STATE_RECONCILED,
    LifecycleStage.AUDIT_CLOSED,
)

MONITORING_ONLY_STAGES: tuple[LifecycleStage, ...] = (
    LifecycleStage.RAW_RECEIVED,
    LifecycleStage.ENVELOPED,
    LifecycleStage.LIGHTWEIGHT_CANONICALIZED,
    LifecycleStage.BASIC_BOUND_OR_KNOWN_SOURCE_MAPPED,
    LifecycleStage.WORLD_STATE_UPDATED,
    LifecycleStage.METRIC_UPDATED,
    LifecycleStage.OPTIONAL_AUDIT_SAMPLED,
)

LIFECYCLE_STAGE_ORDER: dict[PathType, tuple[LifecycleStage, ...]] = {
    PathType.STANDARD: STANDARD_LIFECYCLE_STAGES,
    PathType.EMERGENCY_FAST_PATH: EMERGENCY_FAST_PATH_STAGES,
    PathType.MONITORING_ONLY: MONITORING_ONLY_STAGES,
}

FAILURE_STAGES: frozenset[LifecycleStage] = frozenset(
    {
        LifecycleStage.SAFETY_GATE_BLOCKED,
        LifecycleStage.EMERGENCY_SAFETY_GATE_BLOCKED,
        LifecycleStage.REJECTED_INVALID_SCHEMA,
        LifecycleStage.REJECTED_UNKNOWN_SOURCE,
        LifecycleStage.REJECTED_BINDING_FAILED,
        LifecycleStage.REJECTED_LOW_CONFIDENCE,
        LifecycleStage.REJECTED_STALE_STATE,
        LifecycleStage.REJECTED_INSUFFICIENT_EVIDENCE,
        LifecycleStage.REJECTED_POLICY_DENIED,
        LifecycleStage.REJECTED_APPROVAL_MISSING,
        LifecycleStage.REJECTED_CAPABILITY_UNAVAILABLE,
        LifecycleStage.REJECTED_TARGET_INVALID,
        LifecycleStage.REJECTED_ADAPTER_UNAVAILABLE,
        LifecycleStage.EXECUTION_TIMEOUT,
        LifecycleStage.EXECUTION_FAILED,
        LifecycleStage.FEEDBACK_MISSING,
        LifecycleStage.FEEDBACK_CONFLICT,
        LifecycleStage.RECOVERY_REQUIRED,
        LifecycleStage.MANUAL_OVERRIDE_REQUIRED,
        LifecycleStage.AUDIT_INCOMPLETE,
        LifecycleStage.UNCLASSIFIED_ENTITY_DETECTED,
        LifecycleStage.MAPPING_REVIEW_REQUIRED,
        LifecycleStage.POLICY_CONTEXT_STALE,
    }
)
